language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: a4QXOpkQYjRz1Gxopp3mfRYqP3tJn47Pp7Lvi5QNzYTpgOu+/6i9iNuNQMlWw17Oiakk3Oguw/BeyTJey7SV//b88jNLzItM8goqnTUN4Yz+yoTRch5Fzx7lpY21ml9efyfyO5VHvsIr0NMpKspLmirVi7oeSipOCIt6otaSCqLJMTR3nc3YM/IArPTO+G11x9QkL/sn10X6v8STmmHZO6bvVr+e/4wtq/e8XEWWgBA9YOEiPRIvoHU+44JZb0j0tn5qDoT2eg1msPcwd4BypIKoLadjhYRgaA1M0lfViz51XRZxRCWTM8S4tA5rsu5w/F4/4+lAPWoYQbWORoo+JgoRYtxpEpAzk8EdbCBiZNq0LGD/il0vHRXqzLB77aE6rwndh/t5l1i2W96XmNE74TIwWvo20vjVVyxdHw3UWcZr2vLUrs70CK0zRI+rb0rcSQqyMWx1njHbQm6lDK6kNH1NO/3MucZdM5cXk2VJ9+lw7cyrzTPH+gP2SMkBU8zm5XrelwMGDK4kw7OW7UW6P7paUCn0Cm7cMikPNSeVh/XlXB8krdc0XwKM4BsHFcSEog73YhZE+Gn92q6cl9gY9ky3m2Bs5DtI6TXb489xfKhj9chdnXSV2IJf1TFnj9FY6ucwI5eRL4cjyJKYQ5ET8sezmWxV9JdbjJ0i84rkhV0=
  app: firstappartj
  on:
    repo: artjtbl097/trailApp
