language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: mMlLBxIGqTDHTHow4g1zKy/0UJQxq2aU2ylhy/CNGMXY+04KhL1MtKQnO0ESRLXzBasRcopYRVkp/Ys3zQzsNaqDcy/x7bGWdVcteusukXET9zwT7utfAp6OvtNEBJzh1/Omcd6d/7ngl4Xvj1Tfzc0QDse9y8PmUE5Z84Mk9h+zEyRuO28Mgh6POAYE/eN/1WsQbvrQ+QV8zwKzYuXIySGSj3P2moecMAfjHAtF9jm4zHcJe3sPNfjeuWPOYTnatlNShEnOpJvd97Xht6opaVFtRFqGdm4aPpcEDRtFAYLQCJsLCoGx0MndwjDqyMx8uzxGhgLCkvsgnelLSzj11DAVz09zx9kEQnKW/f9Xzg5lu5fVX9DUNOb9247KTsv3v2LGA14YvzwFqkPsqY0r376frZTb03LhMEfpzThdTAsrdsFn5+1e3iUMjkkFudR1c8cXzZ1/vztII1B4feZyZOH1/mCr5K4AcqShrz/PuqdLafHPOMpPExgrbuKEAY9uyXg1vl4mv20qcKY+1SiDf51VUTpHawlLsn9G5C6Dx8CTz/wtlAe5EKBPfMT7H18Yp8tyZ2kMGce/S1gsmL4wvP4nQfSH4Qy2k+46PmoJNxDsb42ToOZrbPXcZ2cfTeX7ddO/Ua8u+VJ/5Gsb4cCXuLgC/l0iIJR7Td/8bvMj/3g=
  app: firstappartj
  on:
    repo: artjtbl097/trailApp
