language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: b0cSa+MdZ2EhNlONEumbStuKh2i5FBmBJiBzSpv8jcOG7S3S/EIqiCCBfSHUKIdM2ZNAPFnYDgt6EEl7W17clC0B4AOkHeeMWV4vHpubQNlfI1fWnS+sTUhG0UtyzVN6NNaVi8yzPfTr3IkhJEyZ2tsP2+0lhIiLUe1yuW0o4XbKk+Tp4wuyU7G67QkGUZNspmHCYT+RSzc6cIIIgNIhKdGfztkb8eptoP+beJmjTBqTvex6CmOn8LeNSTff2rOPNADYXWHr7gCU9GpbxcAN7P/65hh9RRwlyQ0XRJLQ0IoEEJlr/qMvq/aN132SNOXczM2/odMP/oGtObCvHX8ljxShjzkTtLRN6ipAp8hvbl2BgvPplP0z4ykx2T7bZ5tWRbaQzwaITBuIFkyfoFynHxPFnLfn0pkZTR6VC8Ay4i+2uHYqaSmeGzl1s3BwuS1MZEJP40xM4LBd98iMene3sMCX6/n3lcZih/aupPsqeprL6HYfnIun6i4zf5ZnA00kE18TGsLOtdLDcTCN7i4i26e48r3UL5oODWoeIgeQVeLwHxkLmX4zbCCTMshimWQlBKx5LGeExORLZS/MSBnCB7hqqbWDHi63IxkSbUW4rowkWC8XBsxyfuyg+QCnx7ymHNZ8yVngzjguy7Qt0TrA+AR5AGFQJcaKMesbAO7hmtA=
  on:
    repo: artjtbl097/trailApp
