language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
  secure: t8IxSJfecYKDTcl0JqUo9VGugxHwZCJDYZYIA6mWL67OxYPjUngNE1IFa4cg++JN9wjrCoHsEP+/ywKhlA3wIx9LQzWBvplRWn6W1+J5eIjI+W1kGH/GwENWtXVsD/rkc/g1i0BDKMMBYB428qVSH7opbZo75uSJ+Z1OYfhhlTdVtRzGQLomgVJAOfZwKKSvNApeOUN6pF+RIeuVcKLyNz6tnT8lFUe8rWAaPESdm/JacOrBZVXVv5HM56j0ITv4eb+u4PJOsoiiQacqzkldSGiIQmkV/RiQ2YKF5v8EZpMwNVNYjMNhO8QBdhp4VxU1Y0zfAZrsqnDODnaldJbuL3TJytnepiiYN+VB1CRhE79cXBm7T9C0iPK47Naml5vpPS+TRSTBCFlOjPmBRYGeu2n9V7xRvTHV7RTVcGUBYt+UuDjBpffHh0NOsYOWuaU2oVnNJ6dDpEJIWylp2y+NucJFC7X5+nlb8oQojElyGvJnMdERSywUbzvBd0bbgUJ/fi3DIn2ShVJaRG5IVcSF/pgfUfaeuNd/gLC5ff4YkRfx43ZFEfngGp2zRaTHDG9bvImmSGFaVP0qxdLFBHyAxhWMtb9dSm8gzKFewEHmKTYOo9SjyQhCEwvPq7rUaFHBZVGi7J+yWG7jkbQqvNaxcMV4FRNw65H8qB/E1d1EC1M=
  app: firstappartj
  on: 
  repo: artjtbl097/trailApp
